image: docker:latest

stages:
  - stage
  - deploy

services:
  - docker:dind

variables:
  STAGE_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_ID
  STAGE_IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

docker-build-stage:
  stage: stage
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $STAGE_IMAGE_LATEST || true
    - docker build --cache-from $STAGE_IMAGE_LATEST
                   --build-arg REACT_APP_API_URL=$REACT_APP_API_URL
                   --build-arg REACT_APP_API_KEY=$REACT_APP_API_KEY
                   -t $STAGE_IMAGE_LATEST .
    - docker tag $STAGE_IMAGE_LATEST $STAGE_IMAGE
    - docker push $STAGE_IMAGE_LATEST
    - docker push $STAGE_IMAGE
  only:
    - develop

docker-build-production:
  stage: deploy
  before_script:
    - docker login -u "$ACR_USERNAME" -p "$ACR_PASSWORD" "$ACR_REGISTRY"
  script:
    - docker build -t "$ACR_REGISTRY/dctx/rapidpass-approver:latest" .
    - docker tag "$ACR_REGISTRY/dctx/rapidpass-approver:latest" "$ACR_REGISTRY/dctx/rapidpass-approver:$CI_BUILD_ID"
    - docker push "$ACR_REGISTRY/dctx/rapidpass-approver:latest"
    - docker push "$ACR_REGISTRY/dctx/rapidpass-approver:$CI_BUILD_ID"
  only:
    - master
