version:  '3.7'
services:
    rapidpass_approver:
      build:
        dockerfile: Dockerfile
        context: .
      image: dctx/rapidpass-approver:latest
      restart: always
      ports:
        - "3030:3030"
      environment: 
        REACT_APP_API_URL: http://localhost:8080
        CSP_STYLE_SRC: https://fonts.googleapis.com
        CSP_FONT_SRC: https://fonts.gstatic.com
        ALLOW_ORIGIN: '*'


      
