version: '3.7'
networks:
  main:
services:
  keycloak:
    image: quay.io/keycloak/keycloak:9.0.3
    restart: always
    ports:
      - '8082:8080'
    volumes:
      # Linux
      - ./rp-keycloak-theme/rapidpass-approver:/opt/jboss/keycloak/themes/rapidpass-approver
      # Windows
      # - d:\React\rapidpass-dashboard\rp-keycloak-theme\rapidpass-approver:/opt/jboss/keycloak/themes/rapidpass-approver
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: 'true'
    networks:
      main:
        aliases:
          - keycloak
  # rapidpass_approver:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   image: dctx/rapidpass-approver:latest
  #   restart: always
  #   ports:
  #     - '3030:3030'
  #   environment:
  #     REACT_APP_API_URL: http://localhost:8080
  #     CSP_STYLE_SRC: https://fonts.googleapis.com
  #     CSP_FONT_SRC: https://fonts.gstatic.com
  #     CSP_SCRIPT_SRC: https://www.googletagmanager.com
  #     CSP_DEFAULT_SRC: https://www.google-analytics.com
  #     ALLOW_ORIGIN: '*'
  #     REACT_APP_MAINTENANCE: 0
  #     REACT_APP_API_KEY: XXX
