export const AporType = {
  AG: { key: 'AG', value: 'Agribusiness & Agricultural Workers' },
  BA: { key: 'BA', value: 'Banks' },
  BP: { key: 'BP', value: 'BPOs & Export-Oriented Business Personnel' },
  CA: { key: 'CA', value: 'Civil Aviation' },
  CM: { key: 'CM', value: 'Capital Market Personnel' },
  DC: { key: 'DC', value: 'Delivery Personnel of Cargoes' },
  DO: { key: 'DO', value: 'Distressed OFWs' },
  EN: { key: 'EN', value: 'EN - Energy Companies' },
  ER: { key: 'ER', value: 'Emergency Responders' },
  FC: { key: 'FC', value: 'Food Chain/ Restaurants' },
  FS: { key: 'FS', value: 'Funeral Service' },
  GO1: { key: 'GO1', value: 'Government Agency - Executive' },
  GO2: { key: 'GO2', value: 'Government Agency - Judicial' },
  GO3: { key: 'GO3', value: 'Government Agency - Legislative' },
  GR: { key: 'GR', value: 'Grocery / Convenience Stores' },
  HM: { key: 'HM', value: 'Heads of Mission/Designated Foreign Mission Reps' },
  HT: { key: 'HT', value: 'Hotel Employees and Tenants' },
  IP: { key: 'IP', value: 'International Passengers and Driver' },
  LW: { key: 'LW', value: 'Logistics Warehouse' },
  ME: { key: 'ME', value: 'Media Personalities' },
  MS: { key: 'MS', value: 'Medical Services' },
  MF: { key: 'MF', value: 'Manufacturing' },
  MT: { key: 'MT', value: 'Money Transfer Services' },
  PH: { key: 'PH', value: 'Pharmacies / Drug Stores' },
  PM: { key: 'PM', value: 'Public Market' },
  SA: { key: 'SA', value: 'SANITATION' },
  SH: { key: 'SH', value: 'Ship Captain & Crew' },
  SS: { key: 'SS', value: 'Security Services' },
  TE: { key: 'TE', value: 'Telecommunications' },
  TF: { key: 'TF', value: 'Transportation Facilities' },
  WC: { key: 'WC', value: 'Water Companies' },
  VE: { key: 'VE', value: 'Veterinary' },
};
