export const AporType = {
  AG: { key: 'AG', value: 'Agribusiness & Agricultural Workers' },
  BA: { key: 'BA', value: 'Banks' },
  BP: { key: 'BP', value: 'BPOs & Export-Oriented Business Personnel' },
  CA: { key: 'CA', value: 'Civil Aviation' },
  CB: { key: 'CB', value: 'Customs Brokerage (Logistic Services)' },
  CM: { key: 'CM', value: 'Capital Market Personnel (Skeletal Workforce)' },
  CY: { key: 'CY', value: 'Container Yards (Logistic Services)' },
  DC: { key: 'DC', value: 'Delivery personnel of cargoes  (Should be delivery services)' },
  DE: { key: 'DE', value: 'Delivery Services' },
  DO: { key: 'DO', value: 'Distressed OFWs' },
  DP: { key: 'DP', value: 'Delivery of Parcels' },
  DR: { key: 'DR', value: 'Disaster and Risk Reduction' },
  DS: { key: 'DS', value: 'DOLE Skeletal Staff for TUPAD' },
  EN: { key: 'EN', value: 'Energy Companies' },
  ER: { key: 'ER', value: 'Emergency Responders' },
  FC: { key: 'FC', value: 'Food Chain/ Restaurants' },
  FF: { key: 'FF', value: 'Freight forwarders (Logistics Services)' },
  FS: { key: 'FS', value: 'Funeral Service' },
  GE: { key: 'GE', value: 'Government Agency - Executive' },
  GJ: { key: 'GJ', value: 'Government Agency - Judicial' },
  GL: { key: 'GL', value: 'Government Agency - Legislative' },
  GR: { key: 'GR', value: 'Grocery / Convenience Stores' },
  HM: { key: 'HM', value: 'Heads of Mission/Designated Foreign Mission Reps' },
  HT: { key: 'HT', value: 'Hotel Employees and Tenants' },
  IP: { key: 'IP', value: 'International Passengers and Driver' },
  LW: { key: 'LW', value: 'Logistics Warehouse' },
  ME: { key: 'ME', value: 'Media Personalities' },
  MS: { key: 'MS', value: 'Medical Services' },
  MF: { key: 'MF', value: 'Manufacturing' },
  MT: { key: 'MT', value: 'Money Transfer Services' },
  PH: { key: 'PH', value: 'Pharmacies / Drug Stores' },
  PM: { key: 'PM', value: 'Public Market' },
  PO: { key: 'PO', value: 'Port operators (Logistics Services)' },
  SA: { key: 'SA', value: 'Sanitation' },
  SH: { key: 'SH', value: 'Ship Captain & Crew' },
  SL: { key: 'SL', value: 'Shipping lines' },
  SO: { key: 'SO', value: 'Social Amelioration' },
  SS: { key: 'SS', value: 'Security Services' },
  TE: { key: 'TE', value: 'Telecommunications' },
  TF: { key: 'TF', value: 'Transportation Facilities' },
  TS: { key: 'TS', value: 'Trucking Services' },
  VE: { key: 'VE', value: 'Veterinary' },
  WC: { key: 'WC', value: 'Water Companies' },
  WH: { key: 'WH', value: 'Warehousing (Logistic Services)' },
};
