export const Roles = {
  HAS_VIEW_DETAILS_ACCESS: 'HAS_VIEW_DETAILS_ACCESS',
  HAS_VIEW_RECORD_STATUS: 'HAS_VIEW_RECORD_STATUS',
  HAS_APPROVE_ACCESS: 'HAS_APPROVE_ACCESS',
  HAS_BULK_UPLOAD_ACCESS: 'HAS_BULK_UPLOAD_ACCESS',
  HAS_VIEW_ALL_RECORDS: 'HAS_VIEW_ALL_RECORDS',
};

export default Roles;
